<a href="https://colab.research.google.com/github/shiva-sharma05/pandas-assignment/blob/main/Numpy_Matrix_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Matrix + Pandas Assignment


## Q1. Create a 3×3 NumPy Matrix

### Input
```
1 2 3
4 5 6
7 8 9
```

### Output
```python
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```


In [2]:
import numpy as np
import pandas as pd
arr = np.arange(1,10).reshape((3,3))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Q2. Multiply Matrix by 2

### Input
```python
[[1,2,3],
 [4,5,6],
 [7,8,9]]
```

### Output
```python
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
```


In [3]:
arr = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]])
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


## Q3. Find Row-wise Sum

### Output
```python
[ 6 15 24]
```


In [4]:
from re import A
arr.sum(axis=1)

array([ 6, 15, 24])

## Q4. Find Column-wise Sum

### Output
```python
[12 15 18]
```


In [5]:
arr.sum(axis=0)

array([12, 15, 18])

## Q5. Extract Second Row

### Output
```python
[4 5 6]
```


In [6]:
arr[1]

array([4, 5, 6])

## Q6. Create DataFrame

| Name | Marks |
|------|------|
| Raj | 80 |
| Amit | 70 |
| Neha | 90 |
| Priya | 85 |


In [7]:
df = pd.DataFrame({
    'name' : ['raj' , 'amit' , 'neha' , 'priya'] ,
    'marks' : [80, 70, 90, 85]
})
df

,name,marks
0,raj,80
1,amit,70
2,neha,90
3,priya,85


## Q7. Add Bonus Column

Bonus = Marks + 5

### Expected Output
```
Raj    80   85
Amit   70   75
Neha   90   95
Priya  85   90
```


In [8]:
df['marks'] + 5

,marks
0,85
1,75
2,95
3,90


## Q8. Display Students Having Marks > 80

### Expected Output
```
Neha   90
Priya  85
```


In [9]:
df[df['marks'] > 80]

,name,marks
2,neha,90
3,priya,85


## Q9. Print First Row Using iloc

### Expected Output
```
Raj 80
```


In [10]:
df.loc[0]

,0
name,raj
marks,80


## Q10. Print Third Row Using iloc

### Expected Output
```
Neha 90
```


In [11]:
df.iloc[2]

,2
name,neha
marks,90


## Q11. Print First 2 Rows Using iloc

### Expected Output
```
Raj 80
Amit 70
```


In [12]:
df.iloc[:2]

,name,marks
0,raj,80
1,amit,70


## Q12. Print Only Name Column Using iloc

### Expected Output
```
Raj
Amit
Neha
Priya
```


In [13]:
df.iloc[: , 0]

,name
0,raj
1,amit
2,neha
3,priya


## Q13. Update Amit's Marks to 75

### Expected Output
```
Amit 75
```


In [20]:
df.replace({70 : 75} , inplace=True)
print(df.loc[1, 'name'], df.loc[1, 'marks'])

amit 75


## Q14. Sort DataFrame by Marks (Descending)

### Expected Output
```
Neha  90
Priya 85
Raj   80
Amit  75
```


In [22]:
df.sort_values(by='marks' , ascending=False)

,name,marks
2,neha,90
3,priya,85
0,raj,80
1,amit,75
